### PR TITLE
initial Laravel 5.4 support

### PR DESCRIPTION
**Pull request by chrispecoraro**
Initial laravel 5.4 support

### CODE REVIEW

**Comment by marco-solare** [comment]
Hey Chris, cool, was just looking into LaraAdmin, wondering if there is a 5.4 compatible version of it yet. Your PR Looks good, read through it in its entirety.
Will try to give it a shot the next days, will give you feedback.

**Comment by gdbhosale** [comment]
Hello Chris,

Thanks for the contribution. Will go through the PR and let you know.

Best regards,

**Comment by odin88** [comment]
Any update on this pull request ?

**Comment by clockys** [comment]
It would be great to have support for 5.4 :+1:

**Comment by wardcraigj** [comment]
I just forked this -- looks like it's missing a new webpack.mix.js file in the install folder. I noticed that there is another PR for 5.4 support which includes a webpack file, if you copy that into this repo it works

**Pull request merged**
